allowed-effects:
  - SPEED
  - RESISTANCE
  - STRENGTH
  - HASTE
  - REGENERATION
  - SATURATION
  - JUMP_BOOST
  - NIGHT_VISION
  - WATER_BREATHING
  - FIRE_RESISTANCE
  - INVISIBILITY
  - HEALTH_BOOST
  - ABSORPTION
  - SLOW_FALLING
  - DOLPHINS_GRACE
  - CONDUIT_POWER
  - LUCK
  # ...

# Controls whether players can craft the mace
# In case this is your first time working with this plugin, YOU SHOULD NOT CHANGE THIS AT ALL
# THis will automatically be set to false if a player crafts the mace
mace: true

# Allows or disables automated crafting machines from crafting the mace
# Recommended to leave this as false
AllowCrafter: false
