allowed-effects:
  - SPEED
  - RESISTANCE
  - STRENGTH
  - HASTE
  - REGENERATION
  - SATURATION
  - JUMP_BOOST
  - NIGHT_VISION
  - WATER_BREATHING
  - FIRE_RESISTANCE
  - INVISIBILITY
  - HEALTH_BOOST
  - ABSORPTION
  - SLOW_FALLING
  - DOLPHINS_GRACE
  - CONDUIT_POWER
  - LUCK
  # ...
